### ISSUE TITLE
Private browsing on a phone does not work

### ISSUE THREAD

**Issue by gflofst** [tom-hightower/talli#92]
If your phone's browser is set to private browsing, it does not hold onto the vote. It needs to be investigated if the way things are working is switching out of private browsing mode causing it to lose context or if it just can't work like this and document it.

**Comment by tom-hightower** [comment]
Private browsing clears cookies on exit (or when you leave a site, depending on the implementation).  Our system for holding onto votes is by associating them with a unique voter ID stored as a cookie.  This is how we are able to operate without requiring a login but still have persistent user data between sessions.  Unfortunately this process does not work in private browsing, so a new unique ID is generated each session.

**Comment by tom-hightower** [comment]
Feel free to add comments or reopen this issue if you have any questions about how this works.
