### ISSUE TITLE
Timezone for the close time for an event is not defined

### ISSUE THREAD

**Issue by gflofst** [tom-hightower/talli#93]
Experimenting with 3 possible timezones has revealed that the automatic opening/closing time for the session is based on the machine time for the machine setting the opening/closing time. This needs to be documented.

**Comment by tom-hightower** [comment]
Would it be sufficient to simply show the timezone (either in the form EST or UTC-05:00), or do I need to implement a way for users to select a specific timezone they wish to operate in?

**Comment by gflofst** [comment]
Just list which timezone

**Comment by tom-hightower** [comment]
See the linked pr for a fix
